#include<iostream>
#include<string>
#include<fstream>

using namespace std;

string FileName;

int main() 
{
    cout << "please enter the name of file:(include file type)";
    getline(cin,FileName);
    // Create and open a file in write mode
    ofstream outFile(FileName);

    // Check if the file was successfully opened
    if (outFile.is_open())
     {
        outFile << "Hello, this is content generated by a C++ program." << endl;
        outFile << "Another line of text." << endl;
        cout << "File "<< FileName<< "created and written successfully." << endl;
        // Close the file
        outFile.close();
    } else 
    {
        cerr << "Error: Unable to open file." << endl;
    }

    return 0;
}